### ISSUE TITLE
Publish the working demo on github.io

### ISSUE THREAD

**Issue by JuergenGutsch** [kasuken/stone.css#6]
**Is your feature request related to a problem? Please describe.**
I'm missing a working demo somewhere online

**Describe the solution you'd like**
As a developer, I'd like to see a working demo in the browser before cloning the repo

**Describe alternatives you've considered**
What about an online working demo at stone_css.github.io? 
It's all on GitHub then and easy to maintain.

**Additional context**
n/a

**Comment by kasuken** [comment]
I have updated the readme and I published a demo here: https://kasuken.github.io/stone.css/
